version: '3.3'

services:
  populix-api:
      build:
        context: .
        dockerfile: ./Dockerfile
      container_name: populix-api
      image: populix-api:latest
      
      ports:
          - 4000:4000
      environment:
          - PORT=4000
          - DB_HOST=mysql
          - DB_USER=your_user
          - DB_PASSWORD=your_password
          - DB_PORT=3306
          - DB_NAME=populix
          - SECRET_KEY=your_secret_key
          - ELASTIC_SEARCH_CLOUD_USERNAME=your_cloud_username
          - ELASTIC_SEARCH_CLOUD_PASSWORD=your_cloud_password
          - ELASTIC_SEARCH_CLOUD_ID=your_cloud_id
      networks: 
        - populix-network
      depends_on: 
        - mysql
  mysql:
        container_name: mysql
        image: mysql:8.0.0
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=populix
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
          - "3306"
        ports:
          - "3306:3306"    
        networks:
        volumes: 
            - mysql:/src/mysql/app
        restart: always 
        networks:
          - populix-network
networks:
    populix-network:
      name: populix-network
      driver: bridge
volumes: 
    mysql:
        name: mysql
