version: '3.8'

services:
  populix-api:
      build:
        context: .
        dockerfile: ./Dockerfile
      container_name: populix-api
      image: populix-api:latest
      ports:
          - 4000:4000
      environment:
          - PORT=4000
          
      networks: 
        - populix-network
      depends_on: 
        - mysql-populix
  mysql-populix:
        container_name: mysql-populix
        image: mysql:8.0.0
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=populix
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
          - "3301"
        ports:
          - "3301:3306"    
        networks:
        volumes: 
            - mysql-populix:/src/mysql/app
        restart: always 
        networks:
          - populix-network
networks:
    populix-network:
      name: populix-network
      driver: bridge
volumes: 
    mysql-populix:
        name: mysql-populix
