version: '3.8'

services:
  populix-api:
      container_name: populix-api
      image: populix-api:1.0.0
      ports:
          - 4000:4000
      environment:
          - MONGO_DATABASE_URL=mongodb://mongodb:27017/monster-db
          - BASE_URL=http://localhost:4000
          - PORT=4000
          - AWS_ENDPOINT=YOUR_AWS_ENDPOINT
          - AWS_REGION=YOUR_AWS_REGION
          - AWS_BUCKETNAME=YOUR_AWS_BUCKETNAME
          - AWS_ACCESS_KEY=YOUR_AWS_ACCESS_KEY
          - AWS_SECRET_KEY=YOUR_AWS_SECRET_KEY
      networks: 
        - populix-network
      depends_on: 
        - mongodb
  mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
          - mongo_data:/var/lib/mongo
        ports:
          - "27017:27017"
        networks: 
          - populix-network
networks:
    populix-network:
      name: populix-network
      driver: bridge
volumes: 
    mongo_data:
        name: mongo_data
